### ISSUE TITLE
Daemonize

### ISSUE THREAD

**Issue by csjjpm** [bhj/KaraokeEternal#16]
Hi,
  I've install it into a jail on my freebsd and it works brilliantly.  When I close my jail the server stops.  I've tried to install a symlink rc.d to make it as a service but I get an error 
env: node: no such file or directory

Any idea how I can make it a background service which doesn't stop when I close the console?

Also can I stop it form changing the port number everytime I start the server?
thanks
Paul

**Comment by bhj** [comment]
Hey Paul, thanks for the feedback. Are you trying something similar to [this thread](https://stackoverflow.com/questions/36666940/making-an-npm-script-auto-start-in-a-freebsd-jail) where it's a PATH issue for some reason (see the last comment)? The server script is at `server/main.js`.

The web server port can (currently) only be set from the [CLI](https://www.karaoke-forever.com/docs/#command-line-options) using `-p <number>` or `--port <number>`.

**Comment by bhj** [comment]
Hey @csjjpm, looking at this again I'm still not sure about the node path issue, but am definitely open to improving running as a service. Right now it's left up to the user if they want to [daemonize](https://stackoverflow.com/questions/4018154/how-do-i-run-a-node-js-app-as-a-background-service/29042953#29042953) or maybe [containerize](https://hub.docker.com/r/david510c/karaoke-forever) it. Leaving open to collect better options. Thanks!

**Comment by bhj** [comment]
I think the ultimate solution to this is going to be very OS-dependent so closing this for now. Keeping the server port constant between runs is currently on the [roadmap](#13). Thanks!
