### ISSUE TITLE
Reset Server?

### ISSUE THREAD

**Issue by BND10706** [bhj/KaraokeEternal#26]
I installed on my Mac, lost the Admin access, how do I remove it so i can reinstall?

**Comment by bhj** [comment]
Hi, you can delete the database file at `~/Library/Application Support/Karaoke Forever Server/database.sqlite3` and then restart the server, and it will be back to a fresh install.

If you want to keep the existing database, another option is to create a new user account, then flip that user's `isAdmin` column to `1` using a sqlite database editor (there are a few freely available ones out there). Then restart the server so it picks up that change.

Hope that helps!
