### ISSUE TITLE
[Feature Request] Allow option to refresh specific media folder

### ISSUE THREAD

**Issue by snogrammer** [bhj/KaraokeEternal#27]
My collection has grown pretty large, so it takes about 30 minutes when added new songs to my collection and doing a media refresh. It'd be great to have a way to refresh a specific directory that could be used for newer songs without requiring a full refresh.

**Comment by bhj** [comment]
I agree, but before we go there, there are some optimizations (alluded to in #13) that might do the trick. Would you be willing to test those when implemented?

BTW, if you're running the `@next` version from npm you can start the server with the `--scan` option to run the scanner at startup. Might help a bit in the interim. Appreciate the suggestions; keep 'em coming!

**Comment by snogrammer** [comment]
Sounds good! I can definitely test them out. I'm starting to get back into the JS/React world, so I should be able to help out in the near future with some of these.

**Comment by lgwapnitsky** [comment]
Still would be a great idea. I have a few thousand tracks split by category folders, and waiting for all to be scanned is a bit long...

**Comment by thomasesr** [comment]
Scanning Specific folders would be great! I have a 87000 file main folder which I don't ever mess with (and takes forever to scan) and a folder filled with mp4's I regularly download using yt-dlp. For now I just put the YT folder on the top of the list and stop the scanning after a few seconds when I'm sure it started scanning the big folder. But being able to select which folder to scan would be way more convenient, specially if they start to get bigger.

**Comment by bhj** [comment]
Support for scanning individual media folders has been merged (mostly as a side-effect of the folder watcher feature 😉) and will be in the next release (likely v2)

If anyone is interested in testing, ping me in the `#dev` Discord channel. Thanks!
