### ISSUE TITLE
Just for Song Book Purposes

### ISSUE THREAD

**Issue by Hefner007** [bhj/KaraokeEternal#30]
Good day, 

I am currently a karaoke DJ with my own library if songs. What I would like to know is if your software can allow we to upload my list of songs and have patrons use your app to only send me their song selections?

**Comment by bhj** [comment]
Hi, that is essentially how it works, though it's designed to be used in "real time" where the playlist is ordered by whoever has gone the longest without singing. If you only want to collect song choices for a later date, you could do this as well (the player doesn't have to be running for people to queue songs, and you could just look at the queue to see which songs were chosen). I can't say whether the UI is optimal for that, but it should work.
