### ISSUE TITLE
Node.appendChild: Argument 1 is not an object

### ISSUE THREAD

**Issue by gazugafan** [bhj/KaraokeEternal#33]
On a fresh install, I get the following error immediately after logging in or creating an account...

TypeError
Node.appendChild: Argument 1 is not an object.
Call Stack
 paint/<
  karaoke-forever/./node_modules/react-github-btn/index.js:33:16

![image](https://user-images.githubusercontent.com/854538/129105241-65d6ef66-1829-4594-8f05-dd7d419bcff9.png)

... but after dismissing the error, everything seems to work just fine!

To reproduce...
```
git clone https://github.com/bhj/karaoke-forever.git .
npm install
npm run dev
```
Open the app in a browser (Firefox and Chrome tested) and attempt to login or create a new account.

node v16.4.2
npm 7.18.1
CentOS 8.1

Seems to have something to do with react-github-btn used on the About component, but it all looks fine to me and works as expected when you actually see it.

**Comment by bhj** [comment]
I agree it's annoying, though it only looks like a showstopper due to the error reporting in dev mode. The error seems to be a side-effect of the transition from SignedOutView to SignedInView as an admin. Hopefully a fix can be pushed to `react-github-btn` once tracked down further.

**Comment by gazugafan** [comment]
Ah, yes! Can confirm it only happens in dev mode. Not a big deal then :)

**Comment by bhj** [comment]
I'd love to get it fixed, either by replacing/removing or fixing via PR. Good first issue maybe :)

**Comment by gazugafan** [comment]
Spoiler alert... I've got a giant PR coming your way soon already ;)

But yeah, looks like a really simple dependency to just remove.

**Comment by bhj** [comment]
Submitted a PR: https://github.com/ntkme/react-github-btn/pull/13
